<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NbaTeamStat extends Model
{
    use HasFactory;

    protected $table = 'nba_team_stats';

    protected $fillable = [
        'event_id',
        'team_id',
        'nba_rating',
        'opponent_id',
        'event_date',
        'splits_json',
        'team_ref',
        'competition_ref',
        'blocks',
        'defensive_rebounds',
        'steals',
        'turnover_points',
        'avg_defensive_rebounds',
        'avg_blocks',
        'avg_steals',
        'avg_48_defensive_rebounds',
        'avg_48_blocks',
        'avg_48_steals',
        'largest_lead',
        'disqualifications',
        'flagrant_fouls',
        'fouls',
        'ejections',
        'technical_fouls',
        'rebounds',
        'vorp',
        'avg_minutes',
        'nba_rating',
        'avg_rebounds',
        'avg_fouls',
        'avg_flagrant_fouls',
        'avg_technical_fouls',
        'avg_ejections',
        'avg_disqualifications',
        'assist_turnover_ratio',
        'steal_foul_ratio',
        'block_foul_ratio',
        'avg_team_rebounds',
        'total_rebounds',
        'total_technical_fouls',
        'team_assist_turnover_ratio',
        'steal_turnover_ratio',
        'avg_48_rebounds',
        'avg_48_fouls',
        'avg_48_flagrant_fouls',
        'avg_48_technical_fouls',
        'avg_48_ejections',
        'avg_48_disqualifications',
        'games_played',
        'games_started',
        'double_double',
        'triple_double',
        'assists',
        'field_goals_made',
        'field_goals_attempted',
        'field_goal_pct',
        'free_throws_made',
        'free_throws_attempted',
        'free_throw_pct',
        'offensive_rebounds',
        'points',
        'turnovers',
        'three_point_pct',
        'three_point_field_goals_attempted',
        'three_point_field_goals_made',
        'team_turnovers',
        'total_turnovers',
        'points_in_paint',
        'brick_index',
        'fast_break_points',
        'avg_field_goals_made',
        'avg_field_goals_attempted',
        'avg_three_point_field_goals_made',
        'avg_three_point_field_goals_attempted',
        'avg_free_throws_made',
        'avg_free_throws_attempted',
        'avg_points',
        'avg_offensive_rebounds',
        'avg_assists',
        'avg_turnovers',
        'offensive_rebound_pct',
        'estimated_possessions',
        'avg_estimated_possessions',
        'points_per_estimated_possession',
        'avg_team_turnovers',
        'avg_total_turnovers',
        'three_point_field_goal_pct',
        'two_point_field_goals_made',
        'two_point_field_goals_attempted',
        'avg_two_point_field_goals_made',
        'avg_two_point_field_goals_attempted',
        'two_point_field_goal_pct',
        'shooting_efficiency',
        'scoring_efficiency',
        'avg_48_field_goals_made',
        'avg_48_field_goals_attempted',
        'avg_48_three_point_field_goals_made',
        'avg_48_three_point_field_goals_attempted',
        'avg_48_free_throws_made',
        'avg_48_free_throws_attempted',
        'avg_48_points',
        'avg_48_offensive_rebounds',
        'avg_48_assists',
        'avg_48_turnovers',
    ];

    protected $casts = [
        'splits_json' => 'array',  // Tells Eloquent to handle JSON as a PHP array
    ];
}
